import { USER_PROFILE_STORAGE_KEY } from "@/features/account/profile";
import { LOCAL_ACCOUNT_CREDENTIALS_STORAGE_KEY } from "@/features/account/credentials";
import { CATALOG_STORAGE_KEY } from "@/features/catalog/storage";
import { CLIENTS_STORAGE_KEY } from "@/features/clients/storage";
import {
  ACTIVE_DRAFT_STORAGE_KEY,
  DRAFTS_STORAGE_KEY,
} from "@/features/drafts/storage";
import { LANGUAGE_STORAGE_KEY } from "@/features/i18n/config";
import { FISCAL_SETTINGS_STORAGE_KEY } from "@/features/invoices/fiscal-settings";
import {
  COMPANY_WORKSPACE_STORAGE_KEY,
} from "./company";
import {
  CONVERSION_DRAFT_STORAGE_KEY,
  HISTORY_STORAGE_KEY,
} from "./history";
import { PAYMENT_METHODS_STORAGE_KEY } from "./payment-methods";
import {
  VERIFACTU_EVENTS_STORAGE_KEY,
  VERIFACTU_INSTALLATION_ID_STORAGE_KEY,
  VERIFACTU_RECORDS_STORAGE_KEY,
  VERIFACTU_SETTINGS_STORAGE_KEY,
} from "@/features/verifactu/storage";

export const EXPORTABLE_STORAGE_KEYS = [
  LANGUAGE_STORAGE_KEY,
  LOCAL_ACCOUNT_CREDENTIALS_STORAGE_KEY,
  USER_PROFILE_STORAGE_KEY,
  CLIENTS_STORAGE_KEY,
  CATALOG_STORAGE_KEY,
  DRAFTS_STORAGE_KEY,
  ACTIVE_DRAFT_STORAGE_KEY,
  COMPANY_WORKSPACE_STORAGE_KEY,
  FISCAL_SETTINGS_STORAGE_KEY,
  PAYMENT_METHODS_STORAGE_KEY,
  HISTORY_STORAGE_KEY,
  CONVERSION_DRAFT_STORAGE_KEY,
  VERIFACTU_RECORDS_STORAGE_KEY,
  VERIFACTU_EVENTS_STORAGE_KEY,
  VERIFACTU_INSTALLATION_ID_STORAGE_KEY,
  VERIFACTU_SETTINGS_STORAGE_KEY,
] as const;
